version: "3.6"

services:
  db:
    image: postgres:latest
    volumes:
      - .volumes/postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - "5432:5432"
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "gunicorn charlotte.wsgi:application --workers=5  --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  
volumes:
  db_new:
  _static:
  _media: